"""Replay-safe storage for temporary legacy MySQL sync runs and source rows."""

from sqlalchemy import text

from Model.db import engine


def ensure_legacy_sync_schema():
    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS containermgmt.legacy_sync_runs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                finished_at TIMESTAMPTZ,
                source_database TEXT NOT NULL CHECK (source_database = 'containermgmt'),
                source_fingerprint TEXT NOT NULL,
                status TEXT NOT NULL,
                summary JSONB NOT NULL DEFAULT '{}'::jsonb
            )
        """))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS containermgmt.legacy_sync_rows (
                source_table TEXT NOT NULL,
                source_key TEXT NOT NULL,
                source_hash TEXT NOT NULL,
                source_row JSONB NOT NULL,
                target_table TEXT,
                target_key TEXT,
                target_hash TEXT,
                status TEXT NOT NULL,
                last_run_id BIGINT NOT NULL REFERENCES containermgmt.legacy_sync_runs(id),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                PRIMARY KEY (source_table, source_key)
            )
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_legacy_sync_rows_status
            ON containermgmt.legacy_sync_rows(status)
        """))
