"""
Migration script for Report & Print Template System.
Creates:
  - containermgmt.report_templates
  - containermgmt.report_template_versions
  - containermgmt.report_render_jobs
Seeds standard system templates:
  - purchase_order (ORDERS)
  - defect_report (ORDERS)
  - bl_summary (LOGISTICS)
"""

import json
import logging
from sqlalchemy import text
from Model.db import engine

logger = logging.getLogger("containerMgmt.migrate_report_templates")

# ── Seed Templates Data ────────────────────────────────────────────────────────

PO_TEMPLATE_HTML = """
<div class="report-container">
    <div class="header">
        <div class="brand">
            <h1>PURCHASE ORDER</h1>
            <div class="po-badge">{{ po_number }}</div>
        </div>
        <div class="meta-box">
            <p><strong>Date:</strong> {{ po_date or '—' }}</p>
            <p><strong>Status:</strong> <span class="status-tag">{{ status }}</span></p>
            <p><strong>Stage:</strong> {{ lifecycle_stage or 'Draft' }}</p>
            {% if eta_date %}<p><strong>ETA:</strong> {{ eta_date }}</p>{% endif %}
            <p><strong>Freight:</strong> {{ freight_type }}</p>
        </div>
    </div>

    <div class="parties-grid">
        <div class="party-card">
            <h3>Buyer / Consignee</h3>
            <p class="party-name">{{ org_name }}</p>
            {% if consignee_name %}<p>{{ consignee_name }}</p>{% endif %}
            <p class="subtext">Generated by: {{ generated_by }} on {{ report_date }}</p>
        </div>
        <div class="party-card">
            <h3>Supplier / Vendor</h3>
            {% if show_vendor and supplier_name %}
                <p class="party-name">{{ supplier_name }}</p>
                {% if supplier_address %}<p>{{ supplier_address }}</p>{% endif %}
                {% if supplier_email %}<p>{{ supplier_email }}</p>{% endif %}
            {% else %}
                <p class="party-name">{{ supplier_name or 'Confidential / Restated' }}</p>
            {% endif %}
        </div>
    </div>

    {% if remark %}
    <div class="notes-box">
        <strong>Remarks / Instructions:</strong> {{ remark }}
    </div>
    {% endif %}

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 20%;">SKU / Code</th>
                <th style="width: 45%;">Item Description</th>
                <th style="width: 15%; text-align: right;">Quantity</th>
                {% if show_financials %}
                <th style="width: 15%; text-align: right;">Unit Price</th>
                <th style="width: 15%; text-align: right;">Total ({{ currency }})</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td style="text-align: center;">{{ loop.index }}</td>
                <td><span class="sku-code">{{ item.sku or '—' }}</span></td>
                <td><strong>{{ item.description }}</strong></td>
                <td style="text-align: right;">{{ item.quantity | format_number(0) }} {{ item.unit }}</td>
                {% if show_financials %}
                <td style="text-align: right;">{{ item.unit_price | format_currency(currency) }}</td>
                <td style="text-align: right;">{{ item.total_price | format_currency(currency) }}</td>
                {% endif %}
            </tr>
            {% else %}
            <tr>
                <td colspan="{% if show_financials %}6{% else %}4{% endif %}" style="text-align: center; color: #64748b;">
                    No line items specified.
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if show_financials %}
    <div class="totals-container">
        <div class="totals-summary">
            <div class="totals-row">
                <span>Subtotal / Order Total:</span>
                <strong>{{ total_amount | format_currency(currency) }}</strong>
            </div>
            {% if advance_amount %}
            <div class="totals-row">
                <span>Advance Required / Paid:</span>
                <span>{{ advance_amount | format_currency(currency) }}</span>
            </div>
            {% endif %}
            {% if balance_amount %}
            <div class="totals-row highlight">
                <span>Balance Due:</span>
                <strong>{{ balance_amount | format_currency(currency) }}</strong>
            </div>
            {% endif %}
        </div>
    </div>
    {% endif %}

    <div class="signatures">
        <div class="sig-block">
            <div class="sig-line"></div>
            <p>Authorized Signature (Buyer)</p>
        </div>
        <div class="sig-block">
            <div class="sig-line"></div>
            <p>Supplier Acknowledgment</p>
        </div>
    </div>
</div>
"""

PO_TEMPLATE_CSS = """
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
    color: #1e293b;
    font-size: 12px;
    line-height: 1.5;
}
.report-container { width: 100%; }
.header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    border-bottom: 2px solid #0f172a;
    padding-bottom: 15px;
    margin-bottom: 20px;
}
.brand h1 { margin: 0; font-size: 24px; color: #0f172a; letter-spacing: -0.5px; }
.po-badge { display: inline-block; font-size: 14px; font-weight: 700; color: #2563eb; margin-top: 4px; }
.meta-box { text-align: right; }
.meta-box p { margin: 2px 0; font-size: 11px; }
.status-tag { display: inline-block; background: #e2e8f0; color: #334155; padding: 2px 6px; border-radius: 4px; font-weight: 600; }
.parties-grid {
    display: flex;
    justify-content: space-between;
    margin-bottom: 20px;
}
.party-card {
    width: 48%;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 6px;
    padding: 12px;
}
.party-card h3 { margin: 0 0 6px 0; font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: 600; }
.party-name { font-size: 14px; font-weight: 700; color: #0f172a; margin: 0 0 4px 0; }
.subtext { font-size: 10px; color: #94a3b8; margin-top: 6px; }
.notes-box {
    background: #fffbeb;
    border: 1px solid #fef3c7;
    border-left: 3px solid #f59e0b;
    padding: 8px 12px;
    border-radius: 4px;
    margin-bottom: 20px;
    font-size: 11px;
    color: #92400e;
}
.data-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
}
.data-table th {
    background: #f1f5f9;
    color: #475569;
    font-size: 11px;
    text-transform: uppercase;
    font-weight: 600;
    padding: 8px 10px;
    border-bottom: 1px solid #cbd5e1;
    text-align: left;
}
.data-table td {
    padding: 8px 10px;
    border-bottom: 1px solid #e2e8f0;
    vertical-align: middle;
}
.sku-code { font-family: monospace; font-size: 10px; color: #64748b; background: #f1f5f9; padding: 2px 4px; border-radius: 3px; }
.totals-container {
    display: flex;
    justify-content: flex-end;
    margin-bottom: 30px;
}
.totals-summary {
    width: 40%;
    border-top: 1px solid #cbd5e1;
    padding-top: 8px;
}
.totals-row {
    display: flex;
    justify-content: space-between;
    padding: 4px 0;
    font-size: 12px;
}
.totals-row.highlight {
    border-top: 1px dashed #cbd5e1;
    margin-top: 4px;
    padding-top: 6px;
    font-size: 14px;
    color: #0f172a;
}
.signatures {
    margin-top: 50px;
    display: flex;
    justify-content: space-between;
}
.sig-block {
    width: 40%;
    text-align: center;
}
.sig-line {
    border-top: 1px solid #94a3b8;
    margin-bottom: 6px;
}
.sig-block p {
    font-size: 11px;
    color: #64748b;
    margin: 0;
}
"""

DEFECT_TEMPLATE_HTML = """
<div class="report-container">
    <div class="header">
        <div>
            <h1>{{ title or 'DAMAGE & DEFECT REPORT' }}</h1>
            <div class="ref-badge">{{ defect_number }}</div>
        </div>
        <div class="meta-box">
            <p><strong>Report Date:</strong> {{ discovery_date or report_date }}</p>
            <p><strong>Status:</strong> <span class="status-tag status-{{ status | lower }}">{{ status }}</span></p>
            <p><strong>Severity:</strong> {{ severity or 'STANDARD' }}</p>
            <p><strong>Reference:</strong> {{ container_no or po_number or '—' }}</p>
        </div>
    </div>

    <div class="summary-card">
        <h3>Overview</h3>
        <p><strong>Description:</strong> {{ description or 'No additional description provided.' }}</p>
        <p><strong>Location / Facility:</strong> {{ location or 'Primary Receiving Yard' }}</p>
        <p><strong>Logged By:</strong> {{ logged_by or 'Operations Staff' }} on {{ report_date }}</p>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 8%;">#</th>
                <th style="width: 42%;">Item Affected</th>
                <th style="width: 20%; text-align: right;">Quantity</th>
                <th style="width: 30%;">Notes / Observation</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td style="text-align: center;">{{ loop.index }}</td>
                <td><strong>{{ item.item_description }}</strong></td>
                <td style="text-align: right;">{{ item.quantity_affected | format_number(0) }} {{ item.unit }}</td>
                <td>{{ item.notes or '—' }}</td>
            </tr>
            {% else %}
            <tr>
                <td colspan="4" style="text-align: center; color: #64748b;">No individual affected items cataloged.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_resolved or resolution_type %}
    <div class="resolution-box">
        <h3>Resolution / Settlement</h3>
        <p><strong>Type:</strong> {{ resolution_type or 'Settled' }}</p>
        {% if resolution_notes %}<p><strong>Notes:</strong> {{ resolution_notes }}</p>{% endif %}
        {% if resolved_at %}<p><strong>Resolved On:</strong> {{ resolved_at }}</p>{% endif %}
    </div>
    {% endif %}

    <div class="footer-signoff">
        <p>Inspector Verification: _________________________ &nbsp;&nbsp;&nbsp;&nbsp; Date: _______________</p>
    </div>
</div>
"""

DEFECT_TEMPLATE_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; color: #0f172a; font-size: 12px; line-height: 1.5; }
.header { display: flex; justify-content: space-between; border-bottom: 2px solid #ef4444; padding-bottom: 12px; margin-bottom: 20px; }
.header h1 { margin: 0; font-size: 22px; color: #b91c1c; }
.ref-badge { font-size: 14px; font-weight: 700; color: #0f172a; margin-top: 4px; }
.meta-box { text-align: right; }
.meta-box p { margin: 2px 0; font-size: 11px; }
.status-tag { display: inline-block; padding: 2px 8px; border-radius: 4px; font-weight: 700; font-size: 11px; }
.status-open { background: #fee2e2; color: #991b1b; }
.status-resolved { background: #dcfce7; color: #166534; }
.summary-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; margin-bottom: 20px; }
.summary-card h3 { margin: 0 0 8px 0; font-size: 11px; text-transform: uppercase; color: #64748b; }
.summary-card p { margin: 4px 0; }
.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
.data-table th { background: #f1f5f9; padding: 8px 10px; border-bottom: 1px solid #cbd5e1; font-weight: 600; text-align: left; }
.data-table td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }
.resolution-box { background: #f0fdf4; border: 1px solid #bbf7d0; border-left: 3px solid #22c55e; border-radius: 6px; padding: 12px; margin-bottom: 20px; }
.resolution-box h3 { margin: 0 0 6px 0; font-size: 12px; color: #15803d; text-transform: uppercase; }
.footer-signoff { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 15px; font-size: 11px; color: #64748b; }
"""

BL_TEMPLATE_HTML = """
<div class="report-container">
    <div class="header">
        <div>
            <h1>BILL OF LADING MANIFEST</h1>
            <div class="bl-number">B/L No: {{ bl_number }}</div>
        </div>
        <div class="meta-box">
            <p><strong>Issue Date:</strong> {{ issue_date or '—' }}</p>
            <p><strong>Carrier:</strong> {{ carrier_name or 'Ocean Carrier' }}</p>
            <p><strong>Vessel / Voyage:</strong> {{ vessel_name }} / {{ voyage_no }}</p>
            <p><strong>Route:</strong> {{ port_of_loading }} &rarr; {{ port_of_discharge }}</p>
        </div>
    </div>

    <div class="parties-grid">
        <div class="party-card">
            <h3>Shipper / Exporter</h3>
            <p class="party-name">{{ shipper_name or '—' }}</p>
            {% if shipper_address %}<p>{{ shipper_address }}</p>{% endif %}
        </div>
        <div class="party-card">
            <h3>Consignee / Notify Party</h3>
            <p class="party-name">{{ consignee_name or org_name }}</p>
            {% if notify_party %}<p>{{ notify_party }}</p>{% endif %}
        </div>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 25%;">Container Number</th>
                <th style="width: 15%;">Type / Size</th>
                <th style="width: 15%;">Seal Number</th>
                <th style="width: 20%; text-align: right;">Gross Weight (KG)</th>
                <th style="width: 20%;">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for c in containers %}
            <tr>
                <td style="text-align: center;">{{ loop.index }}</td>
                <td><strong class="container-code">{{ c.container_no }}</strong></td>
                <td>{{ c.container_type or '40 HC' }}</td>
                <td>{{ c.seal_no or '—' }}</td>
                <td style="text-align: right;">{{ c.weight | format_number(0) }}</td>
                <td><span class="status-pill">{{ c.status_name or 'In Transit' }}</span></td>
            </tr>
            {% else %}
            <tr>
                <td colspan="6" style="text-align: center; color: #64748b;">No assigned containers.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="manifest-footer">
        <p>Total Containers Listed: <strong>{{ container_count }}</strong> &nbsp;|&nbsp; Generated on {{ report_date }}</p>
    </div>
</div>
"""

BL_TEMPLATE_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; color: #0f172a; font-size: 12px; line-height: 1.5; }
.header { display: flex; justify-content: space-between; border-bottom: 2px solid #0284c7; padding-bottom: 14px; margin-bottom: 20px; }
.header h1 { margin: 0; font-size: 22px; color: #0369a1; }
.bl-number { font-size: 15px; font-weight: 700; color: #0f172a; margin-top: 4px; }
.meta-box { text-align: right; }
.meta-box p { margin: 2px 0; font-size: 11px; }
.parties-grid { display: flex; justify-content: space-between; margin-bottom: 20px; }
.party-card { width: 48%; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; }
.party-card h3 { margin: 0 0 6px 0; font-size: 11px; text-transform: uppercase; color: #64748b; }
.party-name { font-size: 14px; font-weight: 700; color: #0f172a; margin: 0; }
.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
.data-table th { background: #f0f9ff; color: #0369a1; padding: 8px 10px; border-bottom: 1px solid #bae6fd; font-weight: 600; text-align: left; }
.data-table td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }
.container-code { font-family: monospace; font-size: 13px; color: #0f172a; }
.status-pill { display: inline-block; background: #e0f2fe; color: #0369a1; padding: 2px 6px; border-radius: 4px; font-size: 10px; font-weight: 600; }
.manifest-footer { margin-top: 30px; border-top: 1px solid #cbd5e1; padding-top: 10px; font-size: 11px; color: #64748b; }
"""

DEFAULT_SYSTEM_TEMPLATES = [
    {
        "slug": "purchase_order",
        "name": "Standard Purchase Order",
        "description": "Standard commercial purchase order for procurement with supplier information, line item table, and payment milestones.",
        "category": "ORDERS",
        "resolver_key": "purchase_order",
        "entity_type": "PurchaseOrder",
        "page_size": "A4",
        "orientation": "portrait",
        "output_format": "pdf",
        "html_content": PO_TEMPLATE_HTML.strip(),
        "css_content": PO_TEMPLATE_CSS.strip(),
    },
    {
        "slug": "defect_report",
        "name": "Damage & Defect Report",
        "description": "Official incident report for cargo damage, physical container defects, and discrepancies discovered during warehouse receiving.",
        "category": "ORDERS",
        "resolver_key": "defect_report",
        "entity_type": "DefectReport",
        "page_size": "A4",
        "orientation": "portrait",
        "output_format": "pdf",
        "html_content": DEFECT_TEMPLATE_HTML.strip(),
        "css_content": DEFECT_TEMPLATE_CSS.strip(),
    },
    {
        "slug": "bl_summary",
        "name": "Bill of Lading Manifest",
        "description": "Comprehensive ocean freight summary listing carrier details, sailing route, and assigned sea containers.",
        "category": "LOGISTICS",
        "resolver_key": "bl_summary",
        "entity_type": "BillOfLanding",
        "page_size": "A4",
        "orientation": "portrait",
        "output_format": "pdf",
        "html_content": BL_TEMPLATE_HTML.strip(),
        "css_content": BL_TEMPLATE_CSS.strip(),
    },
]


def ensure_report_templates_schema():
    """
    Idempotent migration to create report templates, versions, and jobs tables,
    and seed initial system templates if missing.
    """
    logger.info("Verifying containermgmt report template tables...")
    with engine.begin() as conn:
        # 1. Report Templates Table
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS containermgmt.report_templates (
                id SERIAL PRIMARY KEY,
                org_id INTEGER REFERENCES usercredentials.organisations(id) ON DELETE CASCADE,
                slug VARCHAR(100) NOT NULL,
                name VARCHAR(255) NOT NULL,
                description TEXT,
                category VARCHAR(50) NOT NULL,
                resolver_key VARCHAR(100) NOT NULL,
                entity_type VARCHAR(100) NOT NULL,
                is_system BOOLEAN NOT NULL DEFAULT FALSE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                page_size VARCHAR(20) DEFAULT 'A4',
                orientation VARCHAR(20) DEFAULT 'portrait',
                output_format VARCHAR(10) DEFAULT 'pdf',
                active_version_id INTEGER,
                default_params JSONB,
                created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
                updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
                is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                deleted_at TIMESTAMP WITHOUT TIME ZONE,
                created_by INTEGER REFERENCES usercredentials.users(id),
                updated_by INTEGER REFERENCES usercredentials.users(id),
                deleted_by INTEGER REFERENCES usercredentials.users(id)
            );

            CREATE UNIQUE INDEX IF NOT EXISTS uq_report_templates_org_slug
                ON containermgmt.report_templates(COALESCE(org_id, 0), slug)
                WHERE is_deleted = FALSE;

            CREATE INDEX IF NOT EXISTS idx_report_templates_category
                ON containermgmt.report_templates(category);

            CREATE INDEX IF NOT EXISTS idx_report_templates_resolver
                ON containermgmt.report_templates(resolver_key);

            CREATE INDEX IF NOT EXISTS idx_report_templates_org
                ON containermgmt.report_templates(org_id);
        """))

        # 2. Report Template Versions Table
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS containermgmt.report_template_versions (
                id SERIAL PRIMARY KEY,
                template_id INTEGER REFERENCES containermgmt.report_templates(id) ONDELETE CASCADE NOT NULL,
                version_number INTEGER NOT NULL DEFAULT 1,
                status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
                html_content TEXT NOT NULL,
                css_content TEXT,
                header_html TEXT,
                footer_html TEXT,
                change_notes TEXT,
                created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
                updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
                is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                deleted_at TIMESTAMP WITHOUT TIME ZONE,
                created_by INTEGER REFERENCES usercredentials.users(id),
                updated_by INTEGER REFERENCES usercredentials.users(id),
                deleted_by INTEGER REFERENCES usercredentials.users(id),
                CONSTRAINT uq_report_template_version UNIQUE (template_id, version_number)
            );

            CREATE INDEX IF NOT EXISTS idx_template_versions_template_id
                ON containermgmt.report_template_versions(template_id);

            CREATE INDEX IF NOT EXISTS idx_template_versions_status
                ON containermgmt.report_template_versions(status);
        """))

        # 3. Report Render Jobs Table
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS containermgmt.report_render_jobs (
                id VARCHAR(36) PRIMARY KEY,
                template_id INTEGER REFERENCES containermgmt.report_templates(id) NOT NULL,
                version_id INTEGER REFERENCES containermgmt.report_template_versions(id),
                org_id INTEGER REFERENCES usercredentials.organisations(id) NOT NULL,
                entity_type VARCHAR(100),
                entity_id INTEGER,
                render_params JSONB,
                status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                output_key VARCHAR(500),
                file_size INTEGER,
                error_message TEXT,
                requested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                completed_at TIMESTAMP WITH TIME ZONE,
                requested_by INTEGER REFERENCES usercredentials.users(id) NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_render_jobs_org_id
                ON containermgmt.report_render_jobs(org_id);

            CREATE INDEX IF NOT EXISTS idx_render_jobs_status
                ON containermgmt.report_render_jobs(status);
        """))

        # 4. Seed Standard System Templates (org_id = NULL)
        for tpl in DEFAULT_SYSTEM_TEMPLATES:
            existing = conn.execute(
                text("""
                    SELECT id, active_version_id 
                    FROM containermgmt.report_templates 
                    WHERE is_system = TRUE AND slug = :slug AND org_id IS NULL AND is_deleted = FALSE
                """),
                {"slug": tpl["slug"]}
            ).fetchone()

            if not existing:
                # Insert template record
                result = conn.execute(
                    text("""
                        INSERT INTO containermgmt.report_templates (
                            org_id, slug, name, description, category, resolver_key,
                            entity_type, is_system, is_active, page_size, orientation,
                            output_format, is_deleted
                        ) VALUES (
                            NULL, :slug, :name, :description, :category, :resolver_key,
                            :entity_type, TRUE, TRUE, :page_size, :orientation,
                            :output_format, FALSE
                        ) RETURNING id;
                    """),
                    {
                        "slug": tpl["slug"],
                        "name": tpl["name"],
                        "description": tpl["description"],
                        "category": tpl["category"],
                        "resolver_key": tpl["resolver_key"],
                        "entity_type": tpl["entity_type"],
                        "page_size": tpl["page_size"],
                        "orientation": tpl["orientation"],
                        "output_format": tpl["output_format"],
                    }
                )
                template_id = result.scalar()

                # Insert Version 1 as PUBLISHED
                v_res = conn.execute(
                    text("""
                        INSERT INTO containermgmt.report_template_versions (
                            template_id, version_number, status, html_content,
                            css_content, change_notes, is_deleted
                        ) VALUES (
                            :template_id, 1, 'PUBLISHED', :html_content,
                            :css_content, 'Initial system release', FALSE
                        ) RETURNING id;
                    """),
                    {
                        "template_id": template_id,
                        "html_content": tpl["html_content"],
                        "css_content": tpl["css_content"],
                    }
                )
                version_id = v_res.scalar()

                # Link active version
                conn.execute(
                    text("""
                        UPDATE containermgmt.report_templates
                        SET active_version_id = :version_id
                        WHERE id = :template_id;
                    """),
                    {"version_id": version_id, "template_id": template_id}
                )
                logger.info(f"Seeded system report template '{tpl['slug']}' (id={template_id}, version={version_id})")

    logger.info("containermgmt report template schema verification and seeding completed.")


if __name__ == "__main__":
    ensure_report_templates_schema()
    print("Report templates migration executed successfully.")
